name: Koin Build & Test
on: [push]
jobs:
  Build-and-Test:
    runs-on: ubuntu-latest
    steps:
      - run: echo "- KOIN - Build & Test -"

      - name: Check out repository code
        uses: actions/checkout@v2

      - uses: actions/setup-java@v2
        with:
          distribution: "adopt"
          java-version: "11"

      - name: Setup Android SDK
        uses: android-actions/setup-android@v2

      - name: Run CORE tests
        run: cd core && ./test.sh && ./install.sh

      - name: Run Android tests
        run: cd android && ./test.sh

      - name: Run Ktor tests
        run: cd ktor && ./test.sh

      - name: Run Plugins tests
        run: cd plugins && ./test.sh
